### ISSUE TITLE
Alice is inompatible with bloc >=0.9.3

### ISSUE THREAD

**Issue by MattisBrizard** [jhomlala/alice#1]
Hello,

I'm using flutter_bloc 0.7.1 wich is based on bloc 0.9.3 and I want to use your package but there is a version conflict with the bloc package.

`Because every version of alice depends on rxdart ^0.21.0 and bloc >=0.9.3 depends on rxdart >=0.18.1 <0.21.0, alice is incompatible with bloc >=0.9.3.
And because flutter_bloc >=0.6.3 depends on bloc ^0.9.3, alice is incompatible with flutter_bloc >=0.6.3.
So, because MyBlocApp depends on both flutter_bloc ^0.7.1 and alice ^0.0.2, version solving failed.
pub get failed (1)`

Thank you

**Comment by jhomlala** [comment]
Alice is using highest possible version of RxDart, which is 0.2.1. You should ask maintainer of flutter_bloc to upgrade RxDart version to 0.2.1, because flutter_bloc is not up-to-date.

**Comment by jhomlala** [comment]
You should upgrade to flutter_bloc 0.8.0. It supports RxDart 0.2.1.

https://pub.dartlang.org/packages/flutter_bloc#-versions-tab-
