### ISSUE TITLE
[BUG] Alice depends on open_file package that requests dangerous permission android.permission.REQUEST_INSTALL_PACKAGES

### ISSUE THREAD

**Issue by TadashiCZ** [jhomlala/alice#105]
Alice uses open_file package that requests permission that it shouldn't. It should be replaced with open_file_safe or open_filex.

**Comment by tiendung01023** [comment]
@TadashiCZ  If you are not using this permission. You can remove it by adding this code to AndroidManifest.xml
`<uses-permission android:name="android.permission.REQUEST_INSTALL_PACKAGES" tools:node="remove"/>`

**Comment by jhomlala** [comment]
Please update to `0.4.1`.
