### ISSUE TITLE
[BUG] Error count in stats is wrong 

### ISSUE THREAD

**Issue by chinnasamymca** [jhomlala/alice#108]
**Describe the bug**
In the stats view, Error count showing 0 instat of 9. 

**To Reproduce**

**Expected behavior**
The error count should be 9 . 

**Screenshots**
![vp2 1 2](https://user-images.githubusercontent.com/5145041/167838309-586187af-1730-4295-a1ec-5c3670e69544.jpg)

**Flutter doctor**
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.10.5, on macOS 12.3.1 21E258 darwin-arm, locale en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 13.3.1)
[✓] Chrome - develop for the web
[!] Android Studio (not installed)
[✓] IntelliJ IDEA Ultimate Edition (version 2022.1)
[✓] Connected device (1 available)
[✓] HTTP Host Availability

! Doctor found issues in 1 category.

**Alice version**
- Version: 1.3.1

**Smartphone (please complete the following information):**
 - Device:  iPhone 12
 - OS: iOS 15

**Additional context**

**Comment by jhomlala** [comment]
Should be fixed in latest release.
