### ISSUE TITLE
[BUG] Can't use flutter_svg 1.1.0 because of xml dependencies

### ISSUE THREAD

**Issue by uzuki-P** [jhomlala/alice#109]
**Describe the bug**
Alice ^0.2.5 requires xml ^5.3.0.
And because flutter_svg >=1.1.0 depends on xml ^6.0.1, alice ^0.2.5 is incompatible with flutter_svg >=1.1.0.

**To Reproduce**
1. `flutter_svg: ^1.1.0` on `dependencies` AND `alice: ^0.2.5` on `dev_dependencies`

**Expected behavior**
Not conflicted.

**Flutter doctor**
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.0.1, on macOS 12.4 21F79 darwin-arm, locale en-ID)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 13.4)
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.67.2)
[!] Connected device
    ! Error: iPhone is not connected. Xcode will continue when iPhone is connected. (code -13)
[✓] HTTP Host Availability

! Doctor found issues in 1 category.
```

**Alice version**
- Version: 0.2.5

**Comment by jhomlala** [comment]
Please try latest Alice version.
