### ISSUE TITLE
Swift version not specified 

### ISSUE THREAD

**Issue by britannio** [jhomlala/alice#11]
I'm getting this error when building for ios

 - `alice` does not specify a Swift version and none of the targets (`Runner`) integrating it have the `SWIFT_VERSION` attribute set. Please contact the author or set the `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod.

To make it easier to reproduce this I've created an empty app with the alice added [here](https://github.com/britannio/flutter-alice-swift-issue)
 
I've also got the full build log [here](https://app.bitrise.io/build/e46ab493cd244707#?tab=log)

**Comment by jhomlala** [comment]
I'm currently don't have Apple computer, so I'm not unable to fix this issue, but maybe you can try fix it and open PR?

Fix should be easy, just follow these steps: https://github.com/ko2ic/image_downloader/issues/9#issuecomment-471608482

Thanks!

**Comment by britannio** [comment]
@jhomlala I made a pull request with the fix. Thanks.
