### ISSUE TITLE
Support Graphql

### ISSUE THREAD

**Issue by findsantodev** [jhomlala/alice#110]
Is it possible to integrate alice to flutter_graphql? Thank you

**Comment by findsantodev** [comment]
Is there  any documentation about how to use alice on graphql?

**Comment by jhomlala** [comment]
Unfortunately there's no support for interceptors in this GraphQL library: https://github.com/zino-hofmann/graphql-flutter/issues?q=interceptor, which is limitation of creating solution for this library.
