### ISSUE TITLE
[FEATURE] Update chopper dependency to latest

### ISSUE THREAD

**Issue by luis901101** [jhomlala/alice#134]
**Is your feature request related to a problem? Please describe.**
Chopper just released new breaking change version `chopper: ^6.0.0`, so **alice** is conflicting with it.

**Describe the solution you'd like**
Solution will be just to upgrade chopper dependency to use `chopper: ^6.0.0`.

**Describe alternatives you've considered**
Simple workaround so far is just to use override dependency, because **alice** is not affected by the breaking change introduced in new chopper version 6.0.0.

**Comment by jhomlala** [comment]
Fixed. Please use version `0.4.1`.
