### ISSUE TITLE
[BUG] version solving failed with flutter_local_notifications

### ISSUE THREAD

**Issue by berdibekovaG** [jhomlala/alice#138]
because project depends on both alice ^0.3.2 and flutter_local_notifications ^13.0.0, version solving failed. version any didn't help

**Comment by Legendorik** [comment]
As a workaround you can downgrade flutter_local_notifications in your pubspec to version 12
flutter_local_notifications: ^12.0.0

**Comment by jhomlala** [comment]
Fixed. Please use version `0.4.1`.
