### ISSUE TITLE
[CHORE] Updated dependencies

### ISSUE THREAD

**Issue by mark-nicepants** [jhomlala/alice#140]
Mainly needed this because dio 5 is out. Also fixed the lint issues I found. 

PR: https://github.com/jhomlala/alice/pull/139

**Comment by sadi304** [comment]
@jhomlala can we merge this? dio 4 is having some vulnerabilities

**Comment by joknjokn** [comment]
Any ETA?

**Comment by jhomlala** [comment]
Fixed. Please use version `0.4.1`.
