### ISSUE TITLE
[FEATURE] Add a sorting functionality on the Inspector screen

### ISSUE THREAD

**Issue by ericqian-tabcorp** [jhomlala/alice#141]
**Is your feature request related to a problem? Please describe.**
Currently on the Alice Inspector screen, all the request are showing in ascending order, if there are hundreds of requests, and I want to view the latest request, I have to scroll all the way down to the bottom, which is not quite convenient.

**Describe the solution you'd like**
Add a sorting functionalities on the Inspector screen, so we can easily sort the requests in either ascending or descending order

**Comment by Toasbi** [comment]
@ericqian-tabcorp This is already implemented since version 0.1.12(tap the 3 dot menu in the request overview and select the sorting there)
