### ISSUE TITLE
[FEATURE] can we get _isInspectorOpened outside of the package?

### ISSUE THREAD

**Issue by tegarnugroho** [jhomlala/alice#154]
The feature request is asking for the capability to access the _isInspectorOpened feature from outside its current package. At the moment, this feature is confined to internal use within the package. However, the requester is suggesting that allowing external access to _isInspectorOpened would enhance the flexibility and integration potential of the codebase. This change could be beneficial for tasks such as cross-feature coordination or for better monitoring and management across different parts of the project.

**Comment by jhomlala** [comment]
Fixed. Please use version `0.4.1`.
