### ISSUE TITLE
[Feature] Alice didn't use database and store all data in RAM

### ISSUE THREAD

**Issue by EArminjon** [jhomlala/alice#156]
**Describe the bug**
All requests are put in RAM instead of local database which increase and retain high memory usage for ever.
I've some download task (which contain some huge JSON ) and that stuck my app at 500mo or more in memory usage. Sometimes that lead to crash or freeze...

**To Reproduce**
1. Do heavy JSON api call
2. Open devtools and check memory usage

**Expected behavior**
Alice should load in ram only relevant data. Else, all data should be put in a local database (You can avoid SQL and use NOSQL)

**Screenshots**

**Flutter doctor**
Please add flutter doctor output here.

**Alice version**
- Version: 0.3.3

**Smartphone (please complete the following information):**
 - Device: Pixel 7 emulator
 - OS: Android 14 API 34

**Additional context**

**Comment by techouse** [comment]
@jhomlala I have some ideas on how to make this work:
1. [ObjectBox](https://pub.dev/packages/objectbox) - robust NoSQL database
2. [Drift](https://pub.dev/packages/drift) - built atop SQLite

I know from experience that ObjectBox is the fastest way to store and retrieve the data as a stream.

Do you have any suggestions?

CC/ @EArminjon

**Comment by EArminjon** [comment]
SQL not needed i think, a classic NOSQL system is far enough ;)

ObjectBox / Hive / Isaar are good for that I believe.

Using SQL can have some side effect on Android devices because Android SQL only accept 1 READ or WRITE at a time. While iOS accept multiple.

**Comment by techouse** [comment]
Agreed, however, I'd stay away from Hive / Isar as they've not been updated in a while.

**Comment by techouse** [comment]
Also, I wouldn't categorize this as a `BUG` per-se, but rather as a feature, since Alice should not be used in a production environment anyway.

**Comment by techouse** [comment]
Also, I think that `Alice.macCallsCount` should kind of address this already
https://github.com/jhomlala/alice/blob/14f7c8339ad937671f3e0306284e4aeb2723e48e/packages/alice/lib/alice.dart#L42

**Comment by EArminjon** [comment]
Damn didn't see that !

Ty a lot.

Message to the maintainer : If you don't want to implement DB, feel free to close this issue.

**Comment by techouse** [comment]
@EArminjon implementing an optional ObjectBox data store should be doable, however, it will force the user to make additional steps like code generation, etc. Because of that, it should be made into a separate package.

@jhomlala to do this we'll probably have to change 

```dart
final BehaviorSubject<List<AliceHttpCall>> callsSubject = BehaviorSubject.seeded([]);
```

into a `Stream<List<AliceHttpCall>>` so that it can then be also fed from an ObjectBox query stream and use another default `List<AliceCall>` variable to store the `AliceHttpCall`s. The OjectBox package would then store those into a `Box`. Check the example here https://github.com/objectbox/objectbox-dart

I'll try and make a PR in the following days/weeks if we agree that that's the best course of action.

**Comment by jhomlala** [comment]
That's okay but I would like to see persistence as another "plug in" package (like alice_dio etc.). This could be optional for applications which requires this storage.

**Comment by jhomlala** [comment]
> Damn didn't see that !
> 
> Ty a lot.
> 
> Message to the maintainer : If you don't plan to implement DB, feel free to close this issue, this parameters is enough for dev / debug env i believe.

Well it's a valid point to use DB since there can be a lot calls with a lot of data so that's fine.

**Comment by techouse** [comment]
@jhomlala yea, I was planning on a "plug-in" approach, regardless, there will have to be some minor changes done to the core package to accommodate for that.
