### ISSUE TITLE
Alice on tap notification on both android and ios is not woking

### ISSUE THREAD

**Issue by DevThurain** [jhomlala/alice#172]
#Alice 0.4.1
Alice notification on tap is calling my local onDidReceiveNotificationResponse

......
    flutterLocalNotificationPlugin.initialize(initializationSettings,
        onDidReceiveNotificationResponse: (detail) {
      onSelectNotification("payload");
    });

  static Future onSelectNotification(String? payload) async {
    debugPrint("local noti");
    if (payload != null) print('Get payload $payload');
  }
.....

It is using my onDidReceiveNotificationResponse instead of calling Alice core.

**Comment by jhomlala** [comment]
You can differentiate Alice notification by checking payload.
