### ISSUE TITLE
[FEATURE] Split alice features into their own packages

### ISSUE THREAD

**Issue by jamieastley** [jhomlala/alice#173]
**Is your feature request related to a problem? Please describe.**
Alice has too many dependencies which aren't required for basic core functionality (ie. simply just viewing the network logs). This raises transitive dependency issues (such as #159, #160) given that this package seems to be almost-unmaintained, so apps which consume Alice and also depend on these packages (or transitive dependencies of) are stuck being unable to update to the latest versions.

This will be a larger problem soon, given that several packages are out of date and require their latest major version to be used by 1st May to address incoming Privacy Manifest requirements enforced by Apple (temporarily resolved by #171).

**Describe the solution you'd like**
I suggest that the extra "features" of alice be separated into their own package rather than being bundled within the primary alice package:

- `alice_shake`
- `alice_notifications`
- `alice_dio_interceptor`
- `alice_http_client`
- `alice_http_extensions`
- `alice_chopper_client`
- ...etc

This allows users to pick and choose exactly what they want/need without having to pull in redundant transitive dependencies (eg. users who use [http](https://pub.dev/packages/http), are not going to need and should not be required to pull in [dio](https://pub.dev/packages/dio) and so on).

**Describe alternatives you've considered**
The alternative is that if this package isn't going to be actively maintained anymore (or semi-actively reviewing/approving PR's from the community to address these issues), then alice is tech debt that will need to be replaced with an alternative tool.

**Additional context**
If this is a potential way forward, I would be happy to help contribute to these changes to make it happen.

**Comment by jhomlala** [comment]
Done :) Please check latest pre release.
