### ISSUE TITLE
No named parameter with the name 'accentColor'.

### ISSUE THREAD

**Issue by sanjaysharmajw** [jhomlala/alice#176]
Launching lib/main.dart on 22041219I in debug mode...
Running Gradle task 'assembleDebug'...
../../../../../.pub-cache/hosted/pub.dev/alice-0.2.4/lib/ui/page/alice_calls_list_screen.dart:46:13: Error: No named parameter with the name 'accentColor'.
            accentColor: AliceConstants.lightRed),
            ^^^^^^^^^^^
../../../../Flutter/flutter3.13.5/packages/flutter/lib/src/material/theme_data.dart:290:11: Context: Found this candidate, but the arguments don't match.
  factory ThemeData({
          ^
../../../../../.pub-cache/hosted/pub.dev/alice-0.2.4/lib/ui/page/alice_stats_screen.dart:19:13: Error: No named parameter with the name 'accentColor'.
            accentColor: AliceConstants.lightRed),
            ^^^^^^^^^^^
../../../../Flutter/flutter3.13.5/packages/flutter/lib/src/material/theme_data.dart:290:11: Context: Found this candidate, but the arguments don't match.
  factory ThemeData({
          ^
../../../../../.pub-cache/hosted/pub.dev/alice-0.2.4/lib/ui/page/alice_call_details_screen.dart:39:13: Error: No named parameter with the name 'accentColor'.
            accentColor: AliceConstants.lightRed),
            ^^^^^^^^^^^
../../../../Flutter/flutter3.13.5/packages/flutter/lib/src/material/theme_data.dart:290:11: Context: Found this candidate, but the arguments don't match.
  factory ThemeData({
          ^
Target kernel_snapshot failed: Exception

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command '/Users/sanjaysharma/Documents/Flutter/flutter3.13.5/bin/flutter'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by jhomlala** [comment]
Please update to latest Alice release.
