### ISSUE TITLE
cant use alice even after adding navigator key

### ISSUE THREAD

**Issue by jagdishjadeja** [jhomlala/alice#18]
I have added navigator key in this manner

```
final Alice alice = Alice(showNotification: true);
 @override
Widget build(BuildContext context) {
    dio.interceptors.add(alice.getDioInterceptor());    
    return MaterialApp(
         navigatorKey: alice.getNavigatorKey(),
         debugShowCheckedModeBanner: false,
     );
}
```

`Cant start Alice HTTP Inspector. Please add NavigatorKey to your application`
when i click on notification it shows error

**Comment by jhomlala** [comment]
Can you share more code? Your current code seems fine, but I need to look deeper to find the problem.
