### ISSUE TITLE
Dio 3.x incompatibility

### ISSUE THREAD

**Issue by skinadm** [jhomlala/alice#19]
Thank you, Jakub Homlala, for developing the wonderful Alice app.
It helps other people a lot.

After upgrading Dio to version 3.x, it became impossible to use Alice:
"Because alice >=0.0.14 depends on dio ^2.2.1 and myapp depends on dio ^3.0.3, alice >=0.0.14 is forbidden. So, because myapp depends on alice ^0.0.14, version solving failed."

We are looking forward to updating Alice to support Dio 3.x

Bless you!

**Comment by jhomlala** [comment]
Fixed in Alice 0.0.15

**Comment by skinadm** [comment]
Many thanks!
