### ISSUE TITLE
Fix score for alice_objectbox

### ISSUE THREAD

**Issue by jhomlala** [jhomlala/alice#210]
We have score 130/160 for `alice_objectbox` on pub.dev: https://pub.dev/packages/alice_objectbox/score.

We should fix issues reported there to have better score.

**Comment by jhomlala** [comment]
@techouse Maybe you could look into this?

**Comment by techouse** [comment]
Well, I can add more docs, but I'm reluctant to remove `@protected` from the relations as it exposes internal mechanics to the user.

**Comment by jhomlala** [comment]
> Well, I can add more docs, but I'm reluctant to remove `@protected` from the relations as it exposes internal mechanics to the user.

Sure, let's fix what we can.
