### ISSUE TITLE
[BUG] Getting the issue with new flutter release

### ISSUE THREAD

**Issue by UmairRehmat1** [jhomlala/alice#228]
**Describe the bug**

../.pub-cache/hosted/pub.dev/alice-1.0.0-dev.10/lib/ui/calls_list/page/alice_calls_list_page.dart:270:63: Error: The argument type 'String?' can't be assigned to the parameter type 'String' because 'String?' is nullable and 'String' isn't.
            OperatingSystem.isAndroid ? OpenFilex.open(result.path) : null,
                                                              ^
../.pub-cache/hosted/pub.dev/alice-1.0.0-dev.10/lib/model/alice_export_result.dart:5:17: Context: 'path' refers to a public property so it couldn't be promoted.
See http://dart.dev/go/non-promo-public-field
  final String? path;
                ^
../.pub-cache/hosted/pub.dev/alice-1.0.0-dev.10/lib/model/alice_export_result.dart:5:17: Context: 'path' couldn't be promoted because field promotion is only available in Dart 3.2 and above.
See http://dart.dev/go/non-promo-field-promotion-unavailable
  final String? path;
                ^
**To Reproduce**
1. Update the flutter to latest stable. 
2. Run the build after cleaning

**Expected behavior**
application should build.

**Alice version**
- [Version](alice: ^1.0.0-dev.10)

**Comment by techouse** [comment]
@UmairRehmat1 could you please provide a few more details regarding your setup?

**Comment by uzuki-P** [comment]
@techouse 
I try running the `alice_dio` from example and it also failed.

Flutter doctor:
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.24.0, on Microsoft Windows [Version 10.0.22631.3880], locale en-ID)
[✓] Windows Version (Installed version of Windows is version 10 or higher)
[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
[✓] Android Studio (version 2024.1)
[✓] IntelliJ IDEA Community Edition (version 2024.1)
[✓] VS Code (version 1.92.2)
[✓] Connected device (1 available)
[✓] Network resources

• No issues found!
```

**Comment by uzuki-P** [comment]
It's just need to add `!` on [line 270](https://github.com/jhomlala/alice/blob/master/packages/alice/lib/ui/calls_list/page/alice_calls_list_page.dart#L270) 😅

```dart
 secondButtonAction: () =>
            OperatingSystem.isAndroid ? OpenFilex.open(result.path!) : null,
```

**Comment by UmairRehmat1** [comment]
> @UmairRehmat1 could you please provide a few more details regarding your setup?

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.22.3, on macOS 14.5 23F79 darwin-arm64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.1)
[✓] VS Code (version 1.88.0)
[✓] Connected device (4 available)
    ! Error: Browsing on the local area network for Umair’s iphone. Ensure the device is unlocked and attached with a cable or associated
      with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
    ! Error: Browsing on the local area network for MP phone. Ensure the device is unlocked and attached with a cable or associated with the
      same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
[✓] Network resources

alice: (alice: ^1.0.0-dev.10)

**Comment by UmairRehmat1** [comment]
> It's just need to add `!` on [line 270](https://github.com/jhomlala/alice/blob/master/packages/alice/lib/ui/calls_list/page/alice_calls_list_page.dart#L270) 😅
> 
> ```dart
>  secondButtonAction: () =>
>             OperatingSystem.isAndroid ? OpenFilex.open(result.path!) : null,
> ```

Please raise a PR

**Comment by bziembanski** [comment]
Hi @jhomlala, can we get this moving?

**Comment by Sp4Rx** [comment]
What about this?

```
        secondButtonAction: () {
          final path = result.path;
          return path != null ? (OperatingSystem.isAndroid ? OpenFilex.open(path) : null) : null;
        },
```

**Comment by BenderBlog** [comment]
So could the author get going with this issue? I have to use old Flutter SDK for my project because of this...

**Comment by techouse** [comment]
You can always use the PR fork in your pubspec.yaml or even make your own fork and use that until it's merged.
