### ISSUE TITLE
[FEATURE] Update package share_plus to ^10.0.1

### ISSUE THREAD

**Issue by bziembanski** [jhomlala/alice#230]
Would it be possible to update the share_plus to ^10.0.1 package? 

This package uses the newest version of the web package, which might be blocking rest of packages from updating

**Comment by bziembanski** [comment]
bump

**Comment by bziembanski** [comment]
@jhomlala any chance on moving this forward?

**Comment by jhomlala** [comment]
Please update to latest release.
