### ISSUE TITLE
Update rxdart to `0.28.0`

### ISSUE THREAD

**Issue by DDavidPrime** [jhomlala/alice#234]
While migrating project dependencies to the latest, I noticed that the latest `alice: ^0.4.2` (and `alice: ^1.0.0-dev.10` too) depend on an older version of `rxdart` (`0.27.7`). Since we should keep up with the up-to-date versions of the packages, it would be great if alice would include the latest version of `rxdart`.

**Comment by jhomlala** [comment]
Fixed. Please update to latest release.
