### ISSUE TITLE
[FEATURE] Where is getDioInterceptor?

### ISSUE THREAD

**Issue by rikiyanuar** [jhomlala/alice#241]
I noticed that the `getDioInterceptor` method, which was available in previous versions, is missing in the current version. This method was incredibly useful for setting up interceptors seamlessly, and without it, implementing similar functionality requires additional custom setup.

Would it be possible to reintroduce `getDioInterceptor` in upcoming releases? Bringing it back would significantly streamline the integration process and help maintain compatibility with our existing codebase.

Alternatively, if there’s an updated approach for adding interceptors to Dio, could someone guide me on the best way to achieve this? Any assistance would be greatly appreciated.

Thank you for considering this request, and for your continued efforts on this fantastic library!

**Comment by techouse** [comment]
Hey,

Why can't you get them from the `Dio` instance directly as is [demonstrated here](https://github.com/jhomlala/alice/blob/master/docs/usage.md#dio)?

**Comment by samueljiwandono0310** [comment]
hello, i have same problemm i try to use AliceDioAdapter aliceDioAdapter = AliceDioAdapter(); but AliceDioAdapter not found in alice: ^1.0.0-dev.12

**Comment by techouse** [comment]
@samueljiwandono0310 Alice has been split into separate packages and in order to use Dio you have to **also** install https://pub.dev/packages/alice_dio
