### ISSUE TITLE
Feature request: Gracefully handling binary payload

### ISSUE THREAD

**Issue by pixnbit** [jhomlala/alice#34]
For binary file upload requests, the Alice page won't render showing errors. It would be nice to handle this scenario. (Either skip the binary part or have a placeholder etc)

**Comment by jhomlala** [comment]
Can you give more details? Example request code will be helpful.

**Comment by pixnbit** [comment]
I'll provide a sample request in the next few days, please keep the issue open.

**Comment by jhomlala** [comment]
Sure :)

**Comment by jhomlala** [comment]
@pixnbit Any update?

**Comment by pixnbit** [comment]
See below:

![Screenshot_20200507-114857](https://user-images.githubusercontent.com/729730/81333267-2ece9100-9059-11ea-99f9-929cd54904e6.jpg)
![Screenshot_20200507-114901](https://user-images.githubusercontent.com/729730/81333272-2fffbe00-9059-11ea-897f-a33d986d34ee.jpg)
![Screenshot_20200507-114904](https://user-images.githubusercontent.com/729730/81333274-3130eb00-9059-11ea-8cf7-6ed030058b83.jpg)

The body is binary image for face recognition. The request page is not even rendering.

**Comment by jhomlala** [comment]
Can you show your dio request code? It will help me setup test code.

**Comment by pixnbit** [comment]
This the generated Dio code from Flutter Retrofit:
```
  @override
  detect(
      {returnFaceId,
      returnFaceLandmarks,
      returnFaceAttributes,
      recognitionModel,
      returnRecognitionModel,
      detectionModel,
      file}) async {
    const _extra = <String, dynamic>{};
    final queryParameters = <String, dynamic>{
      'returnFaceId': returnFaceId,
      'returnFaceLandmarks': returnFaceLandmarks,
      'returnFaceAttributes': returnFaceAttributes,
      'recognitionModel': recognitionModel,
      'returnRecognitionModel': returnRecognitionModel,
      'detectionModel': detectionModel
    };
    queryParameters.removeWhere((k, v) => v == null);
    final _data = Stream.fromIterable(file.readAsBytesSync().map((i) => [i]));
    final Response<List<dynamic>> _result = await _dio.request('/detect',
        queryParameters: queryParameters,
        options: RequestOptions(
            method: 'POST',
            headers: <String, dynamic>{
              'Content-Type': 'application/octet-stream',
              'Ocp-Apim-Subscription-Key': 'test'
            },
            extra: _extra,
            contentType: 'application/octet-stream',
            baseUrl: baseUrl),
        data: _data);
    var value = _result.data
        .map((dynamic i) => DetectResult.fromJson(i as Map<String, dynamic>))
        .toList();
    return Future.value(value);
  }
```

**Comment by jhomlala** [comment]
Stream request body should be handled starting from version 0.0.32 of Alice.
