### ISSUE TITLE
hardcoded @mipmap/ic_launcher

### ISSUE THREAD

**Issue by Nyan274** [jhomlala/alice#36]
Unhandled Exception: PlatformException(INVALID_ICON, The resource @mipmap/ic_launcher could not be found.

**Comment by jhomlala** [comment]
Hi, when does this occurs? Please provide more details:
* Example code
* Flutter doctor
* Alice version

**Comment by jhomlala** [comment]
Fixed in Alice 0.0.25. Use notificationIcon parameter.
