### ISSUE TITLE
save action is not working on ios

### ISSUE THREAD

**Issue by ekuleshov** [jhomlala/alice#43]
The save action is failing on iOS with "only supported on Android" exception at:

```
MethodChannelPathProvider.getExternalStoragePath (package:path_provider_platform_interface/src/method_channel_path_provider.dart:55:7)
#1      getExternalStorageDirectory (package:path_provider/path_provider.dart:92:39)
#2      AliceSaveHelper._saveToFile (package:alice/helper/alice_save_helper.dart:57:37)
#3      AliceSaveHelper.checkPermissions (package:alice/helper/alice_save_helper.dart:30:7)
```

Need to use different location on iOS

```
    Directory externalDir = await (Platform.isAndroid //
      ? getExternalStorageDirectory() : getApplicationDocumentsDirectory());
```
But because location is private - also need to use something like share_extend plugin (it provides additional options comparing to the share plugin)

It can be used something like this (the sharePositionOrigin is needed for iOS common share UI):

```
    File tempFile = await writeFile(externalDir);

    RenderBox renderBox = _popupMenuKey.currentContext.findRenderObject();
    Offset position = renderBox.localToGlobal(Offset.zero);

    await ShareExtend.share(tempFile.path, "file",
        subject: "Alice Export",
        sharePanelTitle: 'Alice Export',
        sharePositionOrigin: Rect.fromLTWH( //
            position.dx, position.dy, renderBox.size.width, renderBox.size.height)
    );
```

As alternative, could introduce a function parameter in Alice instance, so user can provide their own implementation of saving/sharing files.

**Comment by jhomlala** [comment]
Currently open file package is not being updated by his author thus i need to temporarily block open file feature in Alice. This issue should be fixed partially. Please reopen this issue if you'll encounter problem again.

**Comment by ekuleshov** [comment]
Please reconsider using platform share instead of saving to a file. The file is not accessible by other apps on ios and using share will also allow to save to a file.

Besides, you already using share to share individual entries.

Thank you
