### ISSUE TITLE
Unhandled Exception: MissingPluginException

### ISSUE THREAD

**Issue by azamatdev** [jhomlala/alice#46]
After updating alice to the latest version 33, it stops showing notification and shows this error.

[ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method initialize on channel dexterous.com/flutter/local_notifications)
E/flutter (23178): #0      MethodChannel._invokeMethod 
package:flutter/…/services/platform_channel.dart:154
E/flutter (23178): <asynchronous suspension>
E/flutter (23178): #1      MethodChannel.invokeMethod 
package:flutter/…/services/platform_channel.dart:329
E/flutter (23178): #2      AndroidFlutterLocalNotificationsPlugin.initialize  (package:flutter_local_notifications/src/platform_flutter_local_notifications.dart:67:27)
E/flutter (23178): #3      FlutterLocalNotificationsPlugin.initialize  (package:flutter_local_notifications/src/flutter_local_notifications_plugin.dart:97:13)
E/flutter (23178): #4      AliceCore._initializeNotificationsPlugin  (package:alice/core/alice_core.dart:66:38)
E/flutter (23178): #5      new AliceCore  (package:alice/core/alice_core.dart:39:7)
E/flutter (23178): #6      new Alice  (package:alice/alice.dart:36:18)
E/flutter (23178): #7      AgroApiProvider.alice 
package:agro_new/network/AgroApiProvider.dart:32
E/flutter (23178): #8      AgroApiProvider.alice 
package:agro_new/network/AgroApiProvider.dart:32
E/flutter (23178): #9      new AgroApiProvider 
package:agro_new/network/AgroApiProvider.dart:35
E/flutter (23178): #10     WinnApplication.onCreate 
E/flutter (23178): #11     _rootRunUnary  (dart:async/zone.dart:1192:38)
E/flutter (23178): #12     _CustomZone.runUnary  (dart:async/zone.dart:1085:19)
E/flutter (23178): #13     _FutureListener.handleValue  (dart:async/future_impl.dart:141:18)
E/flutter (23178): #14     Future._propagateToListeners.handleValueCallback  (dart:async/future_impl.dart:682:45)
E/flutter (23178): #15     Future._propagateToListeners  (dart:async/future_impl.dart:711:32)
E/flutter (23178): #16     Future._completeWithValue  (dart:async/future_impl.dart:526:5)
E/flutter (23178): #17     _AsyncAwaitCompleter.complete  (dart:async-patch/async_patch.dart:36:15)
E/flutter (23178): #18     _completeOnAsyncReturn  (dart:async-patch/async_patch.dart:298:13)
E/flutter (23178): #19     sharedgetInstance (package:agro_new/data/sharedPref.dart)
E/flutter (23178): #20     _rootRunUnary  (dart:async/zone.dart:1192:38)
E/flutter (23178): #21     _CustomZone.runUnary  (dart:async/zone.dart:1085:19)
E/flutter (23178): #22     _FutureListener.handleValue  (dart:async/future_impl.dart:141:18)
E/flutter (23178): #23     Future._propagateToListeners.handleValueCallback  (dart:async/future_impl.dart:682:45)
E/flutter (23178): #24     Future._propagateToListeners  (dart:async/future_impl.dart:711:32)
E/flutter (23178): #25     Future._completeWithValue  (dart:async/future_impl.dart:526:5)
E/flutter (23178): #26     Future._asyncComplete.<anonymous closure>  (dart:async/future_impl.dart:556:7)
E/flutter (23178): #27     _rootRun  (dart:async/zone.dart:1184:13)
E/flutter (23178): #28     _CustomZone.run  (dart:async/zone.dart:1077:19)
E/flutter (23178): #29     _CustomZone.runGuarded  (dart:async/zone.dart:979:7)
E/flutter (23178): #30     _CustomZone.bindCallbackGuarded.<anonymous closure>  (dart:async/zone.dart:1019:23)
E/flutter (23178): #31     _microtaskLoop  (dart:async/schedule_microtask.dart:43:21)
E/flutter (23178): #32     _startMicrotaskLoop  (dart:async/schedule_microtask.dart:52:5)

`  Alice alice = Alice(showNotification: true);
  AgroApiProvider() {
    dio = new Dio(options);
    dio.interceptors.add(alice.getDioInterceptor());
  }
  Alice getAliceInstance() {
    return alice;
  }
`

this is the constructor of http calls class

`navigatorKey:
            application.apiProvider.getAliceInstance().getNavigatorKey(),`

I added this in main root widget referencing the Http calls class.

**Comment by jhomlala** [comment]
Please try using latest version: 0.1.0.

Also try to use flutter clean and then flutter build.
