### ISSUE TITLE
Log from compute or Isolate

### ISSUE THREAD

**Issue by codeknox** [jhomlala/alice#47]
This library looks pretty good, but the current app I work on requires some offload into Isolates.
I'm having the usual 

I cannot send `Alice` as parameter to the `Isolate`, because:
`Unhandled Exception: Invalid argument(s): Illegal argument in isolate message : (object is a closure - Function '<anonymous closure>':.)`

and off course cannot access Alice instance from there too, so I'm stuck.

Any suggestions?

**Comment by jhomlala** [comment]
Can you paste some minimal example code? It'll be helpful to debug this problem.

**Comment by jhomlala** [comment]
Check this issue here: https://github.com/dart-lang/sdk/issues/38964
You're probably not sending top level function to isolate.
