### ISSUE TITLE
Cant add navigator key for alice inspector

### ISSUE THREAD

**Issue by jigarparmar21** [jhomlala/alice#50]
at define navigatorkey in return WillPopScope navigatorkey shows error
 

 @override
  Widget build(BuildContext context) {
    return WillPopScope(
       navigatorKey: _alice.getNavigatorKey(),
        child: Theme(
            data: ThemeData(
              brightness: Brightness.light,
              primarySwatch: AppColor.appColor,
              primaryColor: AppColor.white,
              buttonTheme: ButtonThemeData().copyWith(
                  buttonColor: AppColor.appColor,
                  textTheme: ButtonTextTheme.primary),
              fontFamily: "EncodeSans",
            ),
            child: layout()),
            
        onWillPop: () {
          return handleBackPress();
        });
  }

**Comment by jigarparmar21** [comment]
Is there any one who can solve this?

**Comment by jhomlala** [comment]
Duplicate: https://github.com/jhomlala/alice/issues/51
