### ISSUE TITLE
 Cant start Alice HTTP Inspector. Please add NavigatorKey to your application

### ISSUE THREAD

**Issue by jigarparmar21** [jhomlala/alice#51]
navigatorKey has already been added to the code, still it shows error(red line) under the navigatorKey.

@override
Widget build(BuildContext context) {
return WillPopScope(
navigatorKey: _alice.getNavigatorKey(),
child: Theme(
data: ThemeData(
brightness: Brightness.light,
primarySwatch: AppColor.appColor,
primaryColor: AppColor.white,
buttonTheme: ButtonThemeData().copyWith(
buttonColor: AppColor.appColor,
textTheme: ButtonTextTheme.primary),
fontFamily: "EncodeSans",
),
child: layout()),

    onWillPop: () {
      return handleBackPress();
    });
}

**Comment by SAGARSURI** [comment]
It should be added to the `MaterialApp`

**Comment by jhomlala** [comment]
You need to add navigator key in MaterialApp widget.
