### ISSUE TITLE
Alternative to navigatorKey

### ISSUE THREAD

**Issue by stepanzalis** [jhomlala/alice#53]
Is there another way how to show inspector app without **navigatorKey**? I'm using [auto_route package](https://pub.dev/packages/auto_route) and when **navigatorKey** is provided, it does not work.

**Comment by jhomlala** [comment]
You need to create wrapper. Check auto_route author answer here:
https://github.com/Milad-Akarie/auto_route_library/issues/100#issuecomment-626336644
https://github.com/Milad-Akarie/auto_route_library/issues/100#issuecomment-626337519

**Comment by Dalakoti07** [comment]
@stepanzalis can you please help me with this? I am also using auto_route and alice. Unable to get this working

**Comment by vincentcastagna** [comment]
@Dalakoti07  see my answer in the other issue mentioned here.
