### ISSUE TITLE
Chopper interceptor has error, Bad state: No element error

### ISSUE THREAD

**Issue by hongjianxun** [jhomlala/alice#55]
some request has this error in chopper, did some has the same error:

Caught error: Bad state: No element
#0      ListMixin.firstWhere (dart:collection/list.dart:150:5)
    #1      AliceCore._selectCall (package:alice/core/alice_core.dart:261:8)
    #2      AliceCore.addResponse (package:alice/core/alice_core.dart:230:34)
    #3      AliceChopperInterceptor.onResponse (package:flutter_capp/net/interceptor/alice_chopper_response_interceptor.dart:124:15)
    #4      ChopperClient._interceptResponse (package:chopper/src/base.dart:200:23)
    <asynchronous suspension>
    #5      ChopperClient.send (package:chopper/src/base.dart:308:17)

**Comment by jhomlala** [comment]
Fixed in 0.0.14.
