### ISSUE TITLE
This package depends too many packages

### ISSUE THREAD

**Issue by lam-nv** [jhomlala/alice#57]
Hi @jhomlala,

I found some packages:
- https://pub.dev/packages/video_player
- https://pub.dev/packages/chopper
- https://pub.dev/packages/chewie
Are they actually used for example or development/tools? No need for production?

Kindly check and provide an update to move these package to dev_dependencies instead.

Many thanks,

**Comment by jhomlala** [comment]
Hi,
all of these libraries are used in Alice.
* video_player and chewie are used to display video files from HTTP response.
* chopper is one of the http libraries supported in Alice

If you have any dependency version issues, you can always use dependency override: https://dart.dev/tools/pub/dependencies#dependency-overrides

**Comment by hpoul** [comment]
+1 for reducing dependencies, maybe make multiple packages if people need those dependencies. Maybe you could reopen this issue, as it is valid imho.
One can certainly overwrite dependency versions, but it's not possible to remove dependencies using dependency overrides.
