### ISSUE TITLE
[BUG] alice incompatible with new version of flutter_local_notifications

### ISSUE THREAD

**Issue by Allyanora** [jhomlala/alice#61]
**Describe the bug**
Alice version ^0.1.5 is not compatible with flutter_local_notifications package, version ^3.0.1+6

**To Reproduce**
1. Import Alice in a project that needs flutter_local_notifications ^3.0.1+6
2. save pubspec.yaml or run pub get
3. see console output: _Because alice 0.1.5 depends on flutter_local_notifications ^1.4.4+4 and no versions of alice match >0.1.5 <0.2.0, alice ^0.1.5 requires flutter_local_notifications ^1.4.4+4._

**Expected behavior**
Upgrade required functions inside alice that uses code from flutter_local_notifications newest updates (from what I saw, the major changes are that timezone is added and the schedule() function is changed to zonedSchedule(), that requires additional parameters in order to properly function)

**Flutter doctor**
[✓] Flutter (Channel stable, 1.22.4, on Mac OS X 10.15.7 19H15 darwin-x64, locale en-RO)
    • Flutter version 1.22.4 at /Users/*/Applications/flutter
    • Framework revision 1aafb3a8b9 (3 weeks ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/*/Library/Android/sdk
    • Platform android-30, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.10.0

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 49.0.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (1 available)
    • iPhone 12 Pro Max (mobile) • 07C5C7D7-5CAB-4AD3-B323-83E381AD312E • ios • com.apple.CoreSimulator.SimRuntime.iOS-14-2 (simulator)

• No issues found!

**Alice version**
- Version: ^0.1.5

**Smartphone (please complete the following information):**
 - Device: all

**Comment by jhomlala** [comment]
Thanks for reporting. Fixed in Alice 0.1.6.

**Comment by Vayth** [comment]
If I may add here, the `flutter_local_notification` now has a new major version `4.0.0`, which you may want to check as well.
