### ISSUE TITLE
how to disable automatic page switching ??

### ISSUE THREAD

**Issue by rakafajars** [jhomlala/alice#67]
i use alice, but i have a little problem. that is, when i move pages .. alice appears, what i want is not to appear when moving pages. just display in the notification and I'll click the notification.

  // set default configs
```
  Dio _dio() {
    final options = BaseOptions(
      baseUrl: _baseUrl,
      connectTimeout: 60000,
      receiveTimeout: 50000,
      contentType: 'application/json',
    );

    var dio = Dio(options);

    dio.interceptors.add(LogginInterceptors());
    Alice alice = Alice(
      showNotification: true,
      // darkTheme: false,
      navigatorKey: navigatorKey,
      // showInspectorOnShake: false,
    );
    dio.interceptors.add(
      alice.getDioInterceptor(),
    );
    alice.showInspector();

    return dio;
  }
```

How do I deactivate Alice when I move the navigate page, I only want Alice to appear in the notification and I can click the notification to bring up the information

**Comment by Vayth** [comment]
Do not call alice.showInspector() here. It is used to show the UI.
