### ISSUE TITLE
[BUG] can not install

### ISSUE THREAD

**Issue by richman666888** [jhomlala/alice#73]
always appear this error while run command : flutter run -- 
"This project uses AndroidX dependencies, but the 'android.useAndroidX' property is not enabled. Set this property to true in the gradle.properties file and retry.  .... "

but if I remove :  alice: ^0.1.11 in pubspec.yaml , it is fine !

PS :  gradle.properties has these below lines already : 
android.useAndroidX=true
android.enableJetifier=true

**Comment by jhomlala** [comment]
Alice doesn't use any Platform (native) code, so issue is not triggered by Alice. Check if you're using stable flutter version. Try to create clear project and import Alice within.
