### ISSUE TITLE
[FEATURE] Add sorting options 

### ISSUE THREAD

**Issue by kightsonsanom** [jhomlala/alice#82]
**Is your feature request related to a problem? Please describe.**
It would be useful to have the most recent requests at the top of the list instead of having to scroll all the way to the bottom. This seems to me like one of the fundamental features. This was already requested in [this](https://github.com/jhomlala/alice/issues/63) issue but I couldn't find a way to filter the requests, only to specify their limit. The documentation also doesn't say anything about it.

**Describe the solution you'd like**
Sort parameter in the Alice constructor.

**Comment by jhomlala** [comment]
Fixed in 0.2.2. Alice will have descending sorting option as default.
