### ISSUE TITLE
[FEATURE] Redundant dependencies

### ISSUE THREAD

**Issue by IlyaMax** [jhomlala/alice#86]
**Is your feature request related to a problem? Please describe.**
This package depends on better_player, dio, chopper and http. Sometimes it can lead to problems. For example our app depends on simple video_player and Im not sure why but it has conflicts with better player because of which app crashed every time we use video player. 

**Describe the solution you'd like**
It could be easily fixed if you remove dependency of better player and create another package as extention to this for some users of package. The same for dio/chopper/http. I do not want to have useless chopper and http dependencies in my project if I use dio as I wouldn't want to have dio if I use chopper. Of course for every http package should be created extension package so users could choose one for their needs.

**Comment by jhomlala** [comment]
Won't do. This will lead to large amount of sub projects which need to maintained. No time for that, sorry. This is debug dependency, you don't need to include it in dependencies section. If you're having problems with dependencies you can try to  override dependencies in `pubspec.yaml`. Also feel free to fork to customize Alice behavior for your purposes.

**Comment by nEdAy** [comment]
I think better_player should be removed, it's not a necessary feature, please keep it a pure Dark library.
