### ISSUE TITLE
[FEATURE] Add custom navigation callback

### ISSUE THREAD

**Issue by ltropin** [jhomlala/alice#88]
I use the plugin to the author and it does not provide for its architecture it is impossible to make a transition to the screen with Alice.

**Solution:**
Use custom callback override navigation function. Maybe someone is using another plugin with routing.

**Comment by jhomlala** [comment]
@ltropin This plugin is only for debug purposes, I don't think so there's special need to architecture it within the app. Anyway could you elaborate more why it's not working in your case? You didn't provide any useful details. Please provide details or I'll close this ticket.

**Comment by ltropin** [comment]
@jhomlala I am use **[auto_route](https://pub.dev/packages/auto_route)** plugin for navigation between screens.
And **Navigator** not working for my application. Because i am use **CupertinoApp.router** with **rootRouter.delegate**, where not working **Navigator.of(context).push(...)**
```dart
CupertinoApp.router(
              title: 'AppName',
              theme: CupertinoTheme.of(context),
              routerDelegate: rootRouter.delegate(),
              routeInformationParser: rootRouter.defaultRouteParser(),
              localizationsDelegates: const [
                Locales.delegate,
                RefreshLocalizations.delegate,
                GlobalMaterialLocalizations.delegate,
                GlobalCupertinoLocalizations.delegate,
                GlobalWidgetsLocalizations.delegate
              ],
              supportedLocales: Locales.delegate.supportedLocales,
            )
```

**Comment by ltropin** [comment]
Fix it. I add in routing:

```
CupertinoRoute(
    path: '/alice',
    page: AliceCallsListScreen,
  )
```

from:

**import 'package:alice/ui/page/alice_calls_list_screen.dart';**

**Comment by goaldtesting** [comment]
@shigomany I'm facing the same issue, how did you call this? as it looks like you need to pass an instance of AliceCore

**Comment by shigomany** [comment]
> @shigomany I'm facing the same issue, how did you call this? as it looks like you need to pass an instance of AliceCore

I'm call:

```dart
AutoRouter.of(context).push(const AliceCallsRoute());
```

Where `AliceCallsRoute` generated.

**Comment by vincentcastagna** [comment]
@shigomany Hey there? Could you be clearer when you say generated ? What did you annotate with `@RoutePage` ?  I'm also using auto route.

**Comment by shigomany** [comment]
> @shigomany Hey there? Could you be clearer when you say generated ? What did you annotate with `@RoutePage` ? I'm also using auto route.

I haven't used it for a long time)

I then used **auto_route** and I need to use it to make a transition to the screen with Alice.

For auto_route (navigator 2.0), it is necessary that all routes are registered.

Therefore, I created such a route where **@AutoRouterConfig(replaceInRouteName: 'Page,Route')** was created.

```dart
CupertinoRoute(
    path: '/alice',
    page: AliceCallsListScreen,
  )
```

And build_runner for auto_route just generated: **AliceCallsRoute** (such a class for the transition)

**Comment by vincentcastagna** [comment]
@shigomany thanks for your answer. But there is something I don't understand on your statement` page: AliceCallsListScreen` can't work. Your should run `build_runner `to indeed ref the generated route in the page argument of your CupertinoRoute (So something like `AliceCallsListRoute.page` ... that's what's blocking me. I can't annotate the Alice screen with @RoutePage for the `build_runner `to do his job. 
Thanks.
