### ISSUE TITLE
[FEATURE] Option to hide share button

### ISSUE THREAD

**Issue by uzuki-P** [jhomlala/alice#91]
**Is your feature request related to a problem? Please describe.**
I'm using small screen android emulator and the share button is in the way. 
![image](https://user-images.githubusercontent.com/16524713/128875510-5ce483d7-d918-4470-9871-bd04df26f361.png)

**Describe the solution you'd like**
An option to hide share button on `Alice` initialization should be fine. Or an option on http call details itself.

**Comment by jhomlala** [comment]
Added support for hiding share button in 0.2.5.
