### ISSUE TITLE
[BUG] Flutter Module crashing when going to native / entering the module again

### ISSUE THREAD

**Issue by josipk-cinnamon** [jhomlala/alice#92]
**Describe the bug**
I'm creating a Flutter Module that is triggered while pressing the FAB inside the native Android app.
Using Alice in the Module in order to track API calls I make there.

Everything works as intended, but if I go back to native app using the back button and then go to the Module again by tapping on the FAB, the module crashes.

Disabling Alice completely (even from pubspec.yaml) fixes the issue.

**To Reproduce**
1. Open the Flutter Module from the native app
2. Tap the back button and get back to the native app
3. Open the Module again
4. Module crashes and brings you to the native app

**Expected behavior**
Exiting and entering the Module shouldn't crash it.

**Flutter doctor**
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.4 20F71 darwin-x64, locale
    en-HR)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.2)
[✓] VS Code (version 1.56.2)
[✓] Connected device (2 available)
```

**Alice version**
- Version: 0.2.4

**Smartphone (please complete the following information):**
 - Device: Pixel 3a
 - OS: Android 11

**Comment by jhomlala** [comment]
Thanks for reporting this issue. Can you provide minimal reproducible example for this issue? This will help debug this issue on my side.
