### ISSUE TITLE
[GRAPHQL CLIENT SUPPORT]

### ISSUE THREAD

**Issue by neelansh-creatorstack** [jhomlala/alice#93]
**Is your feature request related to a problem? Please describe.**
I have been trying to use Alice with graphql. And i was not able to as graphql internally used send instead of GET, POST, PUT.
I am using the package flutter_graphql.

**Describe the solution you'd like**
I would like if Alice can also be integrated with grapghQL client.

**Comment by jhomlala** [comment]
https://pub.dev/packages/graphql_flutter library is deprecated: https://github.com/zino-app/graphql-flutter/issues/894

I won't add support for library which won't be maintained. If you still need graphql_flutter support in your app, I recommend using generic http call interface in Alice API.
