### ISSUE TITLE
[BUG] App does not compile on iOS for Swift 4 projects

### ISSUE THREAD

**Issue by kightsonsanom** [jhomlala/alice#99]
**Describe the bug**
App does not compile on iOS if Swift 4 is used in the project (currently default swift version for Flutter projects). Here is related bug https://github.com/jhomlala/betterplayer/issues/776#issuecomment-985991324

**To Reproduce**
1. Add package to the new flutter project,
2. Run the app on iOS (can be simulator)

**Expected behavior**
App compiles and runs

**Flutter doctor**
Please add flutter doctor output here.

**Alice version**
- Version: 0.2.5

**Smartphone (please complete the following information):**
 - Device: iPhone 12
 - OS: 15.0

**Comment by kazbeksultanov** [comment]
I have the same issue. 

flutter doctor -v
[✓] Flutter (Channel stable, 2.8.0, on macOS 11.5.2 20G95 darwin-x64, locale ru)
    • Flutter version 2.8.0 at /Users/kazbek/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision cf44000065 (6 weeks ago), 2021-12-08 14:06:50 -0800
    • Engine revision 40a99c5951
    • Dart version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/kazbek/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Users/kazbek/Library/Java/JavaVirtualMachines/corretto-1.8.0_302/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment Corretto-8.302.08.1 (build 1.8.0_302-b08)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[!] Android Studio
    • Android Studio at /Users/kazbek/Library/Android/sdk/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Android Studio not found at /Users/kazbek/Library/Android/sdk/Contents
    • Try updating or re-installing Android Studio.

[✓] VS Code (version 1.63.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (2 available)
    • iPhone (Kazbek) (mobile) • b0edb6b02db2d949cde254ea5efb94efaeaea98a • ios            • iOS 15.1 19B74
    • Chrome (web)             • chrome                                   • web-javascript • Google Chrome 97.0.4692.99

! Doctor found issues in 1 category.

**Comment by kazbeksultanov** [comment]
I encountered this problem when using the package alice, but actually the problem was generated from better_player

Undefined symbols for architecture arm64: "_OBJC_CLASS_$__TtC13better_player12CacheManager", referenced from: objc-class-ref in BetterPlayerPlugin.o ld: symbol(s) not found for architecture arm64

Solution that helped me was number 3 is this answers. So there was no problem with package
https://stackoverflow.com/a/70280105/7816014

**Comment by jhomlala** [comment]
Please update to `0.4.1`.
